### ISSUE TITLE
DSPSL.dll中计算恒星位置和距离不准确

### ISSUE THREAD

**Issue by drizztwind** [sselecirPyM/DysonSphereProgramSeed#8]
[32091808.txt](https://github.com/sselecirPyM/DysonSphereProgramSeed/files/6636984/32091808.txt)
这里面计算的位置和距离和游戏中看到的完全不一样

**Comment by drizztwind** [comment]
> [32091808.txt](https://github.com/sselecirPyM/DysonSphereProgramSeed/files/6636984/32091808.txt)
> 这里面计算的位置和距离和游戏中看到的完全不一样

这里我反编译了DSPSL.DLL，进行了改造，只对符合条件的星系生成行星资源。名称、光度、行星基本信息、行星类型等都没问题，主要还是恒星位置，恒星与初始星的距离，以及恒星之间的距离计算，和游戏中看到的差异很大。

**Comment by sselecirPyM** [comment]
0.10已修正

**Comment by drizztwind** [comment]
非常感谢！！
